# Generated by Django 2.1.7 on 2019-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='isHeABitch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
